spring:
  cloud:
    gateway:
     routes:
       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/auth/**

       - id: patient-service
         uri: lb://PATIENT-SERVICE
         predicates:
           - Path=/patient/**

       - id: soignant-service
         uri: lb://SOIGNANT-SERVICE
         predicates:
           - Path=/soignant/**

